version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      OPENAI_API_KEY: 'OPENAI_API_KEY'
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_CHATBOT_BASE_URL=http://localhost:8000/api
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
